name: PROD-workflow
run-name: Deploy the project to production
on: [workflow_dispatch]
jobs:
    deploy-production:
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/main' }}
        steps:
            - name: deploy
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "${{ secrets.PRODUCTION_DEPLOY_HOOK }}"
